
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from warnings import catch_warnings
with catch_warnings(record=True):
    import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "062f6f118fe4ea439ae255a8ff886a532e20ecdb",
 "version": "0.21.0.dev+412.g062f6f118"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
